branch-defaults:
  master:
    environment: Samplelogin-env
global:
  application_name: Samplelogin-env
  default_ec2_keyname: XXXXXX
  default_platform: Node.js running on 64bit Amazon Linux/4.9.2
  default_region: ap-south-1
  sc: git
