branch-defaults:
  master:
    environment: Samplelogin-env
global:
  application_name: Samplelogin-env
  default_ec2_keyname: XXXXXX
  default_platform: 64bit Amazon Linux 2018.03 v4.9.2 running Node.js
  default_region: ap-south-1
  sc: git
